package com.gaurav.paypaydemo.stub

import com.gaurav.paypaydemo.datalayer.CountryCurrencyData

fun stubCountryCurrencyData() = listOf<CountryCurrencyData>(
    CountryCurrencyData("INR", 83.0),
    CountryCurrencyData("USD", 1.0),
    CountryCurrencyData("YEN", 0.77),
    CountryCurrencyData("AED", 3.67),
    CountryCurrencyData("AFN", 67.00),
    CountryCurrencyData("ALL", 108.00),
    CountryCurrencyData("AMD", 400.00),
    CountryCurrencyData("ANG", 1.80),
    CountryCurrencyData("AOA", 400.00),
    CountryCurrencyData("ARS", 107.00),
    CountryCurrencyData("AUD", 1.55),
    CountryCurrencyData("AWG", 1.80),
    CountryCurrencyData("AZN", 1.70),
    CountryCurrencyData("BAM", 1.95),
    CountryCurrencyData("BBD", 2.00),
    CountryCurrencyData("BDT", 83.01),
    CountryCurrencyData("BGN", 1.95),
    CountryCurrencyData("BHD", 0.37),
    CountryCurrencyData("BIF", 2000.00),
    CountryCurrencyData("BMD", 1.00),
    CountryCurrencyData("BND", 1.35),
    CountryCurrencyData("BOB", 6.90),
    CountryCurrencyData("BRL", 5.34),
    CountryCurrencyData("BSD", 1.00),
    CountryCurrencyData("BTC", 0.00000001),
    CountryCurrencyData("BTN", 73.00),
    CountryCurrencyData("BWP", 11.00),
    CountryCurrencyData("BYN", 2.53),
    CountryCurrencyData("BYR", 20000.00),
    CountryCurrencyData("BZD", 2.00),
    CountryCurrencyData("CAD", 1.33),
    CountryCurrencyData("CDF", 2000.00),
    CountryCurrencyData("CHF", 0.99),
    CountryCurrencyData("CLF", 0.03),
    CountryCurrencyData("CLP", 910.00),
    CountryCurrencyData("CNY", 7.14),
    CountryCurrencyData("COP", 4100.00),
    CountryCurrencyData("CRC", 625.00),
    CountryCurrencyData("CUC", 1.00),
    CountryCurrencyData("CUP", 25.00),
    CountryCurrencyData("CVE", 100.00),
    CountryCurrencyData("CZK", 25.00),
    CountryCurrencyData("DJF", 170.00),
)

fun stubCountryList() = listOf("INR","YEN","AED","USD","AFN","ALL","AMD","ANG","AOA","ARS","AUD","AWG","AZN","BAM","BBD","BDT","BGN","BHD","BIF","BMD","BND","BOB","BRL","BSD","BTC","BTN","BWP","BYN","BYR","BZD")
